name: Unit Tests
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependency
        run: npm install
      - name: Run tests
        run: npm run test
